import type { ImageEditorToolsState } from "@/components/image-editor.state"

export type FilterPreset = {
  name: string
  description: string
  values: Partial<ImageEditorToolsState>
}

export const FILTER_PRESETS: FilterPreset[] = [
  {
    name: "Normal",
    description: "No filter applied",
    values: {
      brightness: 100,
      contrast: 100,
      saturation: 100,
      exposure: 0,
      temperature: 0,
      gamma: 1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 0,
      noise: 0,
      grain: 0,
    },
  },
  // Hue-based filters
  {
    name: "Sunset",
    description: "Warm orange hue shift",
    values: {
      brightness: 105,
      contrast: 110,
      saturation: 115,
      hue: 30,
      exposure: 5,
      temperature: 0,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 10,
      noise: 0,
      grain: 0,
    },
  },
  {
    name: "Ocean",
    description: "Cool blue hue shift",
    values: {
      brightness: 105,
      contrast: 110,
      saturation: 115,
      hue: -30,
      exposure: 5,
      temperature: 0,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 10,
      noise: 0,
      grain: 0,
    },
  },
  {
    name: "Forest",
    description: "Green hue shift",
    values: {
      brightness: 105,
      contrast: 110,
      saturation: 115,
      hue: 120,
      exposure: 5,
      temperature: 0,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 10,
      noise: 0,
      grain: 0,
    },
  },
  // Tint-based filters
  {
    name: "Golden Hour",
    description: "Warm golden tint",
    values: {
      brightness: 110,
      contrast: 105,
      saturation: 100,
      hue: 0,
      exposure: 10,
      temperature: 20,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 20,
      grayscale: 0,
      tint: 0,
      vibrance: 5,
      noise: 0,
      grain: 0,
    },
  },
  {
    name: "Blue Hour",
    description: "Cool blue tint",
    values: {
      brightness: 105,
      contrast: 110,
      saturation: 100,
      hue: 0,
      exposure: 5,
      temperature: -20,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 5,
      noise: 0,
      grain: 0,
    },
  },
  {
    name: "Rose Gold",
    description: "Pink tint with warm tones",
    values: {
      brightness: 110,
      contrast: 105,
      saturation: 100,
      hue: 0,
      exposure: 10,
      temperature: 15,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 10,
      grayscale: 0,
      tint: 0,
      vibrance: 5,
      noise: 0,
      grain: 0,
    },
  },
  // Combined effects
  {
    name: "Vintage Rose",
    description: "Hue shift with warm tint",
    values: {
      brightness: 105,
      contrast: 110,
      saturation: 90,
      hue: 15,
      exposure: 5,
      temperature: 15,
      gamma: 1,
      vintage: 20,
      blur: 0,
      invert: 0,
      sepia: 15,
      grayscale: 0,
      tint: 0,
      vibrance: 0,
      noise: 5,
      grain: 10,
    },
  },
  {
    name: "Moody Blue",
    description: "Hue shift with cool tint",
    values: {
      brightness: 100,
      contrast: 115,
      saturation: 90,
      hue: -15,
      exposure: 0,
      temperature: -15,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 0,
      noise: 0,
      grain: 5,
    },
  },
  // Original filters
  {
    name: "Clarendon",
    description: "High contrast, slightly warm",
    values: {
      brightness: 105,
      contrast: 120,
      saturation: 110,
      exposure: 5,
      temperature: 10,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 10,
      noise: 0,
      grain: 0,
    },
  },
  {
    name: "Gingham",
    description: "Vintage, slightly faded",
    values: {
      brightness: 105,
      contrast: 110,
      saturation: 90,
      exposure: 0,
      temperature: 5,
      gamma: 1,
      vintage: 20,
      blur: 0,
      invert: 0,
      sepia: 10,
      grayscale: 0,
      tint: 0,
      vibrance: 0,
      noise: 5,
      grain: 10,
    },
  },
  {
    name: "Moon",
    description: "High contrast, black and white",
    values: {
      brightness: 110,
      contrast: 130,
      saturation: 0,
      exposure: 10,
      temperature: 0,
      gamma: 1.2,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 100,
      tint: 0,
      vibrance: 0,
      noise: 0,
      grain: 5,
    },
  },
  {
    name: "Lark",
    description: "Light, airy, and bright",
    values: {
      brightness: 115,
      contrast: 105,
      saturation: 90,
      exposure: 15,
      temperature: 5,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 5,
      noise: 0,
      grain: 0,
    },
  },
  {
    name: "Reyes",
    description: "Warm, vintage look",
    values: {
      brightness: 105,
      contrast: 110,
      saturation: 95,
      exposure: 5,
      temperature: 15,
      gamma: 1,
      vintage: 30,
      blur: 0,
      invert: 0,
      sepia: 15,
      grayscale: 0,
      tint: 0,
      vibrance: 0,
      noise: 10,
      grain: 15,
    },
  },
  {
    name: "Juno",
    description: "Warm, vibrant colors",
    values: {
      brightness: 110,
      contrast: 115,
      saturation: 120,
      exposure: 10,
      temperature: 20,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 15,
      noise: 0,
      grain: 0,
    },
  },
  {
    name: "Slumber",
    description: "Soft, dreamy look",
    values: {
      brightness: 105,
      contrast: 95,
      saturation: 90,
      exposure: 5,
      temperature: 10,
      gamma: 1,
      vintage: 0,
      blur: 2,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 0,
      noise: 0,
      grain: 5,
    },
  },
  {
    name: "Crema",
    description: "Warm, creamy tones",
    values: {
      brightness: 110,
      contrast: 105,
      saturation: 95,
      exposure: 10,
      temperature: 15,
      gamma: 1.1,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 10,
      grayscale: 0,
      tint: 0,
      vibrance: 5,
      noise: 0,
      grain: 5,
    },
  },
  {
    name: "Ludwig",
    description: "High contrast, dramatic",
    values: {
      brightness: 105,
      contrast: 125,
      saturation: 110,
      exposure: 5,
      temperature: 0,
      gamma: 1.2,
      vintage: 0,
      blur: 0,
      invert: 0,
      sepia: 0,
      grayscale: 0,
      tint: 0,
      vibrance: 10,
      noise: 0,
      grain: 0,
    },
  },
]
