export const colorPalette = [
  // Row 1: Grayscale
  { color: "#000000", name: "black" },
  { color: "#404040", name: "dark gray" },
  { color: "#606060", name: "gray" },
  { color: "#808080", name: "medium gray" },
  { color: "#a0a0a0", name: "light gray" },
  { color: "#c0c0c0", name: "lighter gray" },
  { color: "#e0e0e0", name: "very light gray" },
  { color: "#f0f0f0", name: "near white" },
  { color: "#fafafa", name: "almost white" },
  { color: "#ffffff", name: "white" },

  // Row 2: Saturated rainbow
  { color: "#ff0000", name: "red" },
  { color: "#ff8000", name: "orange" },
  { color: "#ffff00", name: "yellow" },
  { color: "#00ff00", name: "lime" },
  { color: "#00ffff", name: "cyan" },
  { color: "#0000ff", name: "blue" },
  { color: "#8000ff", name: "indigo" },
  { color: "#ff00ff", name: "magenta" },
  { color: "#ff0080", name: "rose" },
  { color: "#ff0040", name: "pink red" },

  // Row 3: Very light tints
  { color: "#ffe5e5", name: "very light red" },
  { color: "#fff0e5", name: "very light orange" },
  { color: "#ffffe5", name: "very light yellow" },
  { color: "#e5ffe5", name: "very light green" },
  { color: "#e5ffff", name: "very light cyan" },
  { color: "#e5e5ff", name: "very light blue" },
  { color: "#f0e5ff", name: "very light indigo" },
  { color: "#ffe5ff", name: "very light magenta" },
  { color: "#ffd9e5", name: "very light rose" },
  { color: "#ffccd9", name: "very light pink" },

  // Row 4
  { color: "#ffcccc", name: "light red" },
  { color: "#ffe0cc", name: "light orange" },
  { color: "#ffffcc", name: "light yellow" },
  { color: "#ccffcc", name: "light green" },
  { color: "#ccffff", name: "light cyan" },
  { color: "#ccccff", name: "light blue" },
  { color: "#e0ccff", name: "light indigo" },
  { color: "#ffccff", name: "light magenta" },
  { color: "#ffcce0", name: "light rose" },
  { color: "#ffb3cc", name: "light pink" },

  // Row 5
  { color: "#ff9999", name: "soft red" },
  { color: "#ffbb99", name: "soft orange" },
  { color: "#ffff99", name: "soft yellow" },
  { color: "#99ff99", name: "soft green" },
  { color: "#99ffff", name: "soft cyan" },
  { color: "#9999ff", name: "soft blue" },
  { color: "#bb99ff", name: "soft indigo" },
  { color: "#ff99ff", name: "soft magenta" },
  { color: "#ff99bb", name: "soft rose" },
  { color: "#ff80aa", name: "soft pink" },

  // Row 6
  { color: "#ff6666", name: "medium red" },
  { color: "#ff9966", name: "medium orange" },
  { color: "#ffff66", name: "medium yellow" },
  { color: "#66ff66", name: "medium green" },
  { color: "#66ffff", name: "medium cyan" },
  { color: "#6666ff", name: "medium blue" },
  { color: "#9966ff", name: "medium indigo" },
  { color: "#ff66ff", name: "medium magenta" },
  { color: "#ff66aa", name: "medium rose" },
  { color: "#ff6699", name: "medium pink" },

  // Row 7
  { color: "#cc3333", name: "deep red" },
  { color: "#cc6633", name: "deep orange" },
  { color: "#cccc33", name: "deep yellow" },
  { color: "#33cc33", name: "deep green" },
  { color: "#33cccc", name: "deep cyan" },
  { color: "#3333cc", name: "deep blue" },
  { color: "#6633cc", name: "deep indigo" },
  { color: "#cc33cc", name: "deep magenta" },
  { color: "#cc3399", name: "deep rose" },
  { color: "#cc3366", name: "deep pink" },

  // Row 8
  { color: "#990000", name: "dark red" },
  { color: "#994d00", name: "dark orange" },
  { color: "#999900", name: "dark yellow" },
  { color: "#009900", name: "dark green" },
  { color: "#009999", name: "dark cyan" },
  { color: "#000099", name: "dark blue" },
  { color: "#4d0099", name: "dark indigo" },
  { color: "#990099", name: "dark magenta" },
  { color: "#990066", name: "dark rose" },
  { color: "#990033", name: "dark pink" },
]
